version: '3.4'
networks:
  my-network:

services:
  #mailcatcher:
    #container_name: 'smtp_server'
    #networks:
    #   - my-network
    #image: yappabe/mailcatcher
   # ports:
      #- 1025:1025
     # - 1080:1080
  database:
    container_name: Fallah_App_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PFA_1234@
    ports:
      - "8002:1433"
    networks:
      - my-network
  fallah_app:
    container_name: Fallah_App
    image: ${DOCKER_REGISTRY-}fallahapp
    build:
      context: .
      dockerfile: Fallah_App/Dockerfile
    ports:
      - "7005:443"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=fallah_App
      - DB_SA_PASSWORD=PFA_1234@
    networks:
      - my-network
   
